ramaelectricstore/ramaelectric/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import Index, About, Sales, Service, Eservice, Resi, Comm, Contactor, Plumb, Solar,Career,  contact, \
    ItemListView, ItemDetailView, FormAppointmentFormView


#app_name = 'ramaelectric'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('about.html', About.as_view(), name='about'),
    path('service.html', Service.as_view(), name='service'),
    path('sales.html', Sales.as_view(), name='sales'),


    path('eservice.html', Eservice.as_view(), name='eservice'),
    path('resi.html', Resi.as_view(), name='resi'),
    path('comm.html', Comm.as_view(), name='comm'),
    path('contractor.html', Contactor.as_view(), name='contractor'),
    path('solar.html', Solar.as_view(), name='solar'),
    path('plumb.html', Plumb.as_view(), name='plumb'),
    path('career.html', Career.as_view(), name='career'),




    path('items_list.html',  ItemListView.as_view(), name='list'),
    path('ramaelectric/<int:pk>', ItemDetailView.as_view(), name='detail'),
    # path('test_create.html', ItemsCreate.as_view(), name='create'),
    path('appointment.html', FormAppointmentFormView.as_view(), name='appointment'),

    path('contact.html', views.contact, name='contact'),














]

ramaelectricstore/ramaelectricstore/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls.conf import include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ramaelectric.urls')),

    path('', RedirectView.as_view(url='ramaelectric')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ramaelectricstore/ramaelectric/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator, validate_email,validate_slug

# Items model for importing excel or csv file directly through admin panel & convert into model data and same data shows into service page. 


class Items(models.Model):
    name = models.CharField(max_length=20)
    brand = models.CharField(max_length=20, blank=True, null=True)
    item = models.CharField(max_length=20, blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True)
    delivery = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField()
    model_type = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    arrival_date = models.CharField( max_length=20, blank=True, null=True)
    updated_on = models.DateTimeField(auto_now_add=True, editable=False)
    img = models.ImageField(upload_to='images/', blank=True, null=True, default='/images/logo.jpg')

    class Meta:
        ordering = ['-updated_on']

    def __str__(self):
        return self.name

    def __str__(self):
        return str(self.item) + ": Rs. " + str(self.price)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})


class ItemsImage(models.Model):  # for uploding multiple image
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images/', blank=True, null=True, default='/images/logo.jpg')

    def __str__(self):
        return self.items.name

    # @property
    # def image_url(self):
    #     if self.img:
    #         return self.img.url
    #     return '#'


class AppointmentForm(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    message = models.CharField(max_length=200)
    address = models.CharField(max_length=100)
    schedule = models.CharField(max_length=50)
    day = models.CharField(max_length=50, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now_add=True, editable=False, null=True, blank=True)

    def __str__(self):
        return self.name


class ContactPage(models.Model):
    name = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?0?\d{9,13}$',
                                 message="Phone number must be in the format: '+999999999'")
    phone = models.CharField(validators=[phone_regex], max_length=13)
    email = models.EmailField(null=True, blank=True)
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.name

ramaelectricstore/ramaelectric/forms.py
from django import forms
from .models import Items, AppointmentForm, ContactPage
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


class ItemsForm(forms.ModelForm):  # Items Form
    class Meta:
        Model = Items
        fields = '__all__'


class FormAppointmentForm(forms.ModelForm):     # appointment booking form
    class Meta:
        model = AppointmentForm
        fields = '__all__'


class ContactPageForm(forms.Form):            # ContactForm for  contact page
    name = forms.CharField(max_length=25)
    phone = forms.CharField(max_length=12)
    email = forms.EmailField(validators=[validate_email])
    message = forms.CharField(widget=forms.Textarea)







    # def clean_email(self):                                      # fields level validation
    #     email_passed = self.cleaned_data.get("email")
          #email2_passed = self.cleaned_data.get("email2")
    #       required_email = "domain.com"                      if passed email is not a domain email den also show error
    #       if not required_email in email_passed:
    #           raise forms.ValidationError("Note the valid email")
    #         if email2_passed != email_passed:                    #  if we use re-enter email
    #             raise forms.ValidationError("email not match")
    #
    #     return email_passed

    # def clean(self):                                                #  Forms level validation -- non- field -- errors
    #     cleaned_data = super(ContactPageForm,self).clean()
    #     email_passed = self.cleaned_data.get("email")
    #     required_email = "domain.com"
    #     if not required_email in email_passed:
    #         raise forms.ValidationError("Note the valid email")

ramaelectricstore/ramaelectric/views.py
from django.conf.global_settings import EMAIL_HOST_USER
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View

from django.views.generic import ListView, DetailView
from django.views.generic import FormView
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import Items, AppointmentForm
from .forms import ItemsForm, FormAppointmentForm, ContactPageForm


class Index(View):                                # main menu start
    def get(self, request):
        return render(request, 'index.html')


class About(View):
    def get(self, request):
        return render(request, 'about.html')


class Sales(View):
    def get(self, request):
        return render(request, 'sales.html')


class Service(View):
    def get(self, request):
        return render(request, 'service.html')


class Pricing(View):
    def get(self, request):
        return render(request, 'pricing.html')


class Eservice(View):    # service section here
    def get(self, request):
        return render(request, 'eservice.html')


class Resi(View):
    def get(self, request):
        return render(request, 'resi.html')


class Comm(View):
    def get(self, request):
        return render(request, 'comm.html')


class Contactor(View):
    def get(self, request):
        return render(request, 'contractor.html')


class Solar(View):
    def get(self, request):
        return render(request, 'solar.html')


class Plumb(View):
    def get(self, request):
        return render(request, 'plumb.html')


class Career(View):
    def get(self, request):
        return render(request, 'career.html')


def contact(request):            # getting contactPage form data and sending  direct message to the company email and the same email response back to the sender email.

    if request.method == 'GET':
        form = ContactPageForm()
    else:
        form = ContactPageForm(request.POST)

        if form.is_valid():
            message_name = form.cleaned_data['name']
            message_phone = form.cleaned_data['phone']
            message_email = form.cleaned_data['email']
            message_body = form.cleaned_data['message']


            appointment = ' Sender name:__' + message_name + '    Phone:__' + message_phone + '    email:__'\
                          + message_email + '     Message:__' + message_body

            send_mail(
                 'From ' + message_name,  # subject
                 appointment,

                 'Email From' + message_email,  # from sender email
                 [EMAIL_HOST_USER, message_email],  # to my email
                 fail_silently=False,

             )

            return render(request, 'contact.html', {'form': form, 'message_name': message_name})
        messages.info(request, 'Failed Try Again !  with correct information.')
    return render(request, 'contact.html', {'form': form})




class ItemListView(ListView):
    template_name = 'ramaelectric/items_list.html'  # url will be look like this <appname>/<modelname>_list.html
    model = Items


class ItemDetailView(DetailView):
    template_name = 'ramaelectric/items_detail.html'  # url will be look like this <appname>/<modelname>_Detail.html
    model = Items

    # def get_object(self):     # override context data
    #     d_ = self.kwargs.get("pk")
    #     return get_object_or_404(Items, id=d_)
    #

# class ItemsDetail(View):
#     def post(self, request, *args, **kwargs):
#         form = ItemsForm(request.POST or None)
#         if form.is_valid():
#             form.save()
#
#         context = {
#             'form': form
#         }
#         return render(request, 'ramaelectric/test_create.html',  context)


class FormAppointmentFormView(View):
    def get(self, request, *args, **kwargs):
        form = FormAppointmentForm()
        context = {'form': form}
        return render(request, 'appointment.html', context)

    def post(self, request, *args, **kwargs):   # appointment section form data rendering and save to database
        form = FormAppointmentForm(request.POST or None)
        if form.is_valid():
            form.save()

            return render(request, 'appointment.html', {'form': form})

ramaelectricstore/ramaelectric/templates/ramaelectric/items_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Details|Rama Electric Store {% endblock %}

<!-- Output table -->
<!--<style type="text/css">-->
<!--.column {-->
<!--  float: left;-->


<!--   /* Should be removed. Only for demonstration */-->
<!--}-->
<!--.left {-->
<!--  width: 70%;-->
<!--}-->

<!--.right {-->
<!--  width: 30%;-->
<!--}-->
<!--/* Clear floats after the columns */-->
<!--.row:after {-->
<!--  content: "";-->
<!--  display: table;-->
<!--  clear: both;-->
<!--}-->
<!--@media screen and (max-width: 600px) {-->
<!--  .column {-->
<!--    width: 100%;-->
<!--  }-->
<!--}-->
<!--/* zooming section  */-->

<!--</style>-->

{% block content %}


<!--context will come as same name of our model  here is like items -->
    <div class="row">

        <div class="col-7"  style="background-color:white;">

            {% ifequal items.img None %}
                <p>No Image Available</p>
            {% else %}

                <img  src="{{ items.img.url }}"  class="img-responsive thumbnail " style="padding-left: 10px" width="700" height="700">
            {% endifequal %}


          <div class="row">

                {% for im in items.itemsimage_set.all %}  <!-- itemsimage need to write in lowercase even though model name is capital letter in model name -->
                <div class="row">
                    <img  src="{{ im.img.url }}"  class="img-fluid" style=object-fit:contain; width="300" height="300";   alt="">

                </div>
                {% endfor %}

            </div>

        </div>
        <br><br><br>
            <div  class="col-5" style="background-color:white;">
<br><br>
                <h6 style="padding-left: 10px;" ><strong>{{ items.name}}</strong> <span style="padding-left: 70px; "><strong> Rs.</strong> </span>  <span  style="color:#00adef; font-weight:bold; font-size:18px"><strong>{{ items.price|default_if_none:"&nbsp;"}}</strong></span></h6>
                <hr>
                <span  style="padding-left: 10px;line-height: 1"><strong>Size:&nbsp;</strong> </span>   <span style="">{{ items.size}} &nbsp;</span>
                <span style="padding-left: 10px;"><strong>Model:&nbsp;</strong> </span>  <span style="">{{ items.model_type}}</span>
                <span style="padding-left: 10px;"><strong>Brand:&nbsp;</strong> </span>   <span style="">{{ items.brand|default_if_none:"&nbsp;"}} &nbsp;</span>
                <span style="padding-left: 10px;"><strong>Item:&nbsp;</strong> </span>  <span style="">{{ items.item|default_if_none:"&nbsp;"}}</span>

                <p style="padding-left: 10px;line-height: 3">{{ items.description}}</p>
                <p style="padding-left: 10px;">{{ items.delivery|default_if_none:"&nbsp;"}}</p>
                <a href="{% url 'list' %}"  style="padding-left: 20px" >&nbsp;<input type="button" value="Back" class="btn btn-info btn-sm" /></a>
                <br>

        </div>
    </div>




{% endblock %}

ramaelectricstore/ramaelectric/templates/ramaelectric/items_list.html
{% extends 'base.html' %}

{% block content %}


<!--<style>-->
<!--table, th, td {-->

<!--  border-collapse: collapse;-->

<!--}-->
<!--th, td {-->

<!--  text-align: left;-->
<!--}-->

<!--a {-->
<!--  color: hotpink;-->
<!--}-->


<!--</style>-->
        <!-- Output table -->
<center>
    <h6>Items Available</h6>
      <table class="table table-hover table-sm" >


          <thead class="table-primary">
          <tr>
              <th scope="col" style="width:10%; padding-left: 20px" > Items Name</th>
                <th scope="col" style="width:40%">Description </th>
                <th scope="col" style="width:10%">Size</th>
              <th scope="col" style="width:10%" >Brand</th>
              <th scope="col" style="width:10%" >Price</th>
              <th scope="col" style="width:5%" ></th>


              </tr>
          </thead>

          <tbody>
          {% for item in object_list %}
              <tr>
                  <td style="padding-left: 30px;"><a href="{{ item.get_absolute_url  }}" target="_blank">{{ item.name }}</a></td>

                <td>{{ item.description }}</td>
                  <td>{{ item.size }}</td>

                  <td> {{ item.brand|default_if_none:"&nbsp; &nbsp;&nbsp; "}}</td>
                  <td> Rs.   <strong>{{ item.price|default_if_none:"&nbsp; &nbsp; "}} </strong></td>
                  <td> <a href="{{ item.get_absolute_url  }}" target="_blank"><input type="button"  style="margin:0px;" value="Details" class="btn btn-info btn-sm" /></a></td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
    </center>


{% endblock %}

ramaelectricstore/ramaelectric/templates/ramaelectric/messages.html
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <h6><center> <li class="{{ message.tags }}">{{ message }}</li></center></h6>
    {% endfor %}
  </ul>
{% endif %}

ramaelectricstore/ramaelectric/templates/ramaelectric/test_create.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> model create </title>
</head>
<body>
<form action = "" method = 'POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' name='save'>

</form>

</body>
</html>
{% endblock %}